feeds:
  - name: HotNews Romania
    url: https://www.hotnews.ro/rss
  - name: BBC World
    url: http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/world/rss.xml
  - name: BBC Business
    url: http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/business/rss.xml
