settings:
  romania_top: 10
  world_top: 10
  max_total_items: 18          # ca să rămână mesajul scurt
  scan_per_feed: 25            # câte intrări citește din fiecare feed

filters:
  # dacă apare oricare -> exclude articolul (titlu + rezumat + link)
  exclude_any:
    # RO: moarte/violenta/crime
    - mort
    - moarte
    - deced
    - deces
    - ucis
    - omor
    - crim
    - asasin
    - impuscat
    - injunghiat
    - viol
    - jaf
    - furt
    - talhar
    - arestat
    - accident
    - traged
    - incendiu
    - exploz
    - ranit
    - victima
    - spitalizat
    - cadavru

    # EN: death/violence/crime
    - dead
    - death
    - died
    - killed
    - murder
    - homicide
    - shooting
    - stabbed
    - rape
    - robbery
    - arrested
    - crash
    - accident
    - tragedy
    - explosion
    - fire
    - victims
    - injured
    - hospital
    - assault
    - attack

# Surse: separăm România vs Global (ca să nu fie amestec)
feeds:
  romania:
    - name: HotNews
      url: https://www.hotnews.ro/rss

  world:
    - name: BBC World
      url: http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/world/rss.xml
    - name: BBC Business
      url: http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/business/rss.xml
